config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies, except: [:search]
  get 'search_movie', to: 'movies#search'
  get 'search_details', to: 'movies#search_details'
  post 'thumbs_up_movie', to: 'movies#thumbs_up'
  post 'thumbs_down_movie', to: 'movies#thumbs_down'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  require 'http'
  require 'json'
  after_initialize :init
  validates :title, presence: true
  validates :thumbs_up, presence: true
  validates :thumbs_down, presence: true

  def self.get_movie_titles(title)
    response = HTTP.get("http://www.omdbapi.com/?apikey=#{Rails.application.credentials.omdb[:omdb_api_key]}&s=#{title.gsub(' ', '%20')}&type=movie").to_s
    parsed_response = JSON.parse(response)['Search']
  end

  def self.get_movie_details(imdb_id)
    response = HTTP.get("http://www.omdbapi.com/?apikey=#{Rails.application.credentials.omdb[:omdb_api_key]}&i=#{imdb_id}&type=movie").to_s
    parsed_response = JSON.parse(response)
    begin
      new(title: parsed_response['Title'],
          director: parsed_response['Director'],
          release_date: parsed_response['Released'],
          plot: parsed_response['Plot'],
          poster: parsed_response['Poster'])
    rescue StandardError => e
      nil
    end
  end

  def init
    self.thumbs_up ||= 0
    self.thumbs_down ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
require 'uri'

class MoviesController < ApplicationController
  def search
    if params[:title].present?
      @movies = Movie.get_movie_titles(params[:title])
      if @movies
        respond_to do |format|
          format.js { render partial: 'movies/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'No movie with that title was found'
          format.js { render partial: 'movies/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a movie title to search'
        format.js { render partial: 'movies/result' }
      end
    end
  end

  def search_details
    imdb_id = request.params[:format]
    @movie = Movie.get_movie_details(imdb_id)
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def thumbs_up
    @movie = Movie.find_or_initialize_by(
      title: params[:title],
      director: params[:director],
      release_date: params[:release_date],
      plot: params[:plot],
      poster: params[:poster]
    )

    @movie.thumbs_up += 1

    if @movie.save
      flash.now[:success] = 'Your thumbs up was successfully submitted.'
      redirect_to movie_path(@movie)
    else
      flash.now[:danger] = 'Your thumbs up was not submitted.'
      redirect_to move_path(@movie)
    end
  end

  def thumbs_down
    @movie = Movie.find_or_initialize_by(
      title: params[:title],
      director: params[:director],
      release_date: params[:release_date],
      plot: params[:plot],
      poster: params[:poster]
    )

    @movie.thumbs_down += 1

    if @movie.save
      flash.now[:success] = 'Your thumbs down was successfully submitted.'
      redirect_to movie_path(@movie)
    else
      flash.now[:danger] = 'Your thumbs down was not submitted.'
      redirect_to movie_path(@movie)
    end
  end

  private

  def movie_params
    params.permit(:title, :release_date, :director, :poster, :plot, :thumbs_up, :thumbs_down)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer mb-5">
    <small>
      MovieThumbs, Copyright &copy 2020 by <a href="https://github.com/BlueLew">Lewis Cruz</a>
    </small>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "MovieThumbs", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to (fa_icon "search", text: "Search"), root_path, class: "btn btn-success" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieThumbs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/movies/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<div class="container">
  <% if @movies %>
    <div class="row row-cols-1 row-cols-md-2 text-center">
      <% @movies.sort_by{ |movie| movie["Year"] }.each do |movie| %>
        <div class="col-sm-4 mb-5">
          <div class="card card-header w-100 h-100">
            <% if movie["Poster"] == "N/A" %>
              <%= image_tag("movie_popcorn.jpg", width: "300px", height: "500px", class: "mx-auto d-block img-fluid") %>
            <% else %>
              <%= image_tag(movie["Poster"], width: "300px", height: "500px", class: "mx-auto d-block img-fluid") %>
            <% end %>
            <h3 class="text-center"><%= link_to movie["Title"],
              search_details_path(movie["imdbID"]), class: "mt-5" %></h3>
            <h4><%= movie["Year"] %></h4>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/movies/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'movies/result.html' %>'

app/views/movies/_thumbs.html.erb
<div class="row">
  <div class="col-sm-4">
    <%= link_to (fa_icon "thumbs-up 2x"), {:controller => "movies", :action => "thumbs_up", :title => @movie.title, :poster => @movie.poster, :director => @movie.director, :release_date => @movie.release_date, :plot => @movie.plot } , :method=>:post, class: "btn btn-success btn-lg" %>
  </div>
  <div class="col-sm-4">
    <%= link_to (fa_icon "thumbs-down 2x"), {:controller => "movies", :action => "thumbs_down", :title => @movie.title, :poster => @movie.poster, :director => @movie.director, :release_date => @movie.release_date, :plot => @movie.plot } , :method=>:post, class: "btn btn-danger btn-lg" %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="center jumbotron mt-5">
  <h1 class="mt-5">MovieThumbs</h1>
  <div class="search-area">
    <h3>Search Movies</h3>
    <%= form_tag search_movie_path, remote: true, method: :get do %>
      <div class="form-group row">
        <div class="col-sm-7 no-right-padding">
          <%= text_field_tag :title, params[:title], placeholder: "Movie title", autofocus: true, class: "form-control form-control-lg" %>
        </div>
        <div class="col-sm-5 no-left-padding">
          <%= button_tag type: :submit, class: "btn btn-success" do %>
            <%= fa_icon 'search 2x' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div id="results">

</div>

app/views/movies/search_details.html.erb
<div class="container">
  <div class="card mt-5 mb-3 border-dark rounded" style="max-width: 1400px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <% if @movie.poster == "N/A" %>
          <%= image_tag("movie_popcorn.jpg", width: "300px", height: "500px", class: "img-fluid") %>
        <% else %>
          <%= image_tag(@movie.poster, width: "300px", height: "500px", class: "img-fluid") %>
        <% end %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h1 class="card-title"><%= @movie.title %></h1>
          <div class="card-text ml-3">
            <div class="row row-cols-1">
              <h4>Director: <%= @movie.director %></h4>
              <% if !@movie.release_date.nil? %>
                <h4>Release Date: <%= @movie.release_date.strftime("%B %d, %Y") %></h4>
              <% else %>
                <h4>Release Date: N/A</h4>
              <% end %>
              <p><%= @movie.plot %></p>
              <% if @movie.thumbs_up > 0 || @movie.thumbs_down > 0 %>
                <strong>Thumbs Up=</strong> <%= @movie.thumbs_up %>
                <strong>Thumbs Down=</strong> <%= @movie.thumbs_down %>
              <% end %>

              <%= render 'movies/thumbs' %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to (fa_icon "arrow-circle-left", text: "Back to Search"), root_path, class: "btn btn-primary" %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <div class="card mt-5 mb-3 border-dark rounded" style="max-width: 1400px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <% if @movie.poster == "N/A" %>
          <%= image_tag("movie_popcorn.jpg", width: "300px", height: "500px", class: "img-fluid")  %>
        <% else %>
          <%= image_tag(@movie.poster, width: "300px", height: "500px", class: "img-fluid") %>
        <% end %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h1 class="card-title"><%= @movie.title %></h1>
          <div class="card-text ml-3">
            <div class="row row-cols-1">
              <h4>Director: <%= @movie.director %></h4>
              <% if !@movie.release_date.nil? %>
                <h4>Release Date: <%= @movie.release_date.strftime("%B %d, %Y") %></h4>
              <% else %>
                <h4>Release Date: N/A</h4>
              <% end %>
              <p><%= @movie.plot %></p>

              <%= render 'movies/thumbs' %>

              <% if @movie.thumbs_up > 0 || @movie.thumbs_down > 0 %>
                <div class="row">
                  <div class="col-sm-4">
                    Up Votes: <%= @movie.thumbs_up %>
                  </div>
                  <div class="col-sm-4">
                    Down Votes: <%= @movie.thumbs_down %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to (fa_icon "arrow-circle-left", text: "Back to Search"), root_path, class: "btn btn-primary" %>
</div>